name: Animated Contribution Snake

on:
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      contents: write

    steps:
      - name: Checkout output branch
        uses: actions/checkout@v3
        with:
          ref: output
          path: output  # Checkout to output/ subdirectory

      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: output/latest-contribution.svg?palette=github-dark&snake=#ADD8E6&background=#000080

      - name: Verify SVG was generated
        run: |
          if [ ! -f "output/latest-contribution.svg" ]; then
            echo "Error: SVG file was not generated!"
            exit 1
          fi
          if ! grep -q '<svg' output/latest-contribution.svg; then
            echo "Error: Invalid SVG content!"
            exit 1
          fi

      - name: Commit and push changes
        run: |
          cd output
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add latest-contribution.svg
          git diff --cached --quiet || git commit -m "Update contribution snake SVG"
          git push