# .github/workflows/scheduler.yml (or any name you like)
name: Animated Contribution Scheduler

on:
  schedule:
    - cron: "0 */8 * * *"
  workflow_dispatch:

jobs:
  trigger-snake:
    uses: ./.github/workflows/snake.yml
    permissions:
      contents: write
    secrets: inherit
